- name: ensure https transport
  package:
    name: apt-transport-https
    state: present
    update_cache: true

- name: add apt key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: add apt repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: install vscode
  package:
    name: code
    state: present

- name: copy libs
  copy:
    src: /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
    dest: /usr/share/code/libxcb.so.1.1.0

- name: create link
  file:
    src: /usr/share/code/libxcb.so.1.1.0
    dest: /usr/share/code/libxcb.so.1
    state: link

- name: fix libs
  lineinfile:
    path: /usr/share/code/libxcb.so.1.1.0
    regexp: "BIG-REQUESTS"
    line: "_IG-REQUESTS"
